apiVersion: v1
kind: Service
metadata:
  namespace: platform
  labels:
    app: kite-cine-web
  name: kite-cine-web
spec:
  type: ClusterIP
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    app: kite-cine-web

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: platform
  labels:
    app: kite-cine-web
  name: kite-cine-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kite-cine-web
  template:
    metadata:
      labels:
        app: kite-cine-web
    spec:
      imagePullSecrets:
        - name: gitlab-registry-credentials
      containers:
        - name: kite-cine-web
          image: imageandtag
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
